### ISSUE TITLE
Date value out of range

### ISSUE THREAD

**Issue by dfirhoze** [AbdulRhmanAlfaifi/CryptnetURLCacheParser#2]
I've tried parsing the three CertUtil folders with both the exe and python versions and each time I get the below error regarding the date values. Appreciate your expertise!

![image](https://github.com/user-attachments/assets/e9b9ff4c-ca2e-4398-a57d-3cb2b2d34ee8)

**Comment by AbdulRhmanAlfaifi** [comment]
Hello there!
From the image you shared, I see that you specified the directory `CryptnetUrlCache` in the `-d` argument, but you need to specify the `MetaData` directory. So, just add `\MetaData` to the end of the directory

**Comment by dfirhoze** [comment]
Oops!! My mistake! Thanks for correcting my path :)
